### ISSUE TITLE
検索・ページングの実装

### ISSUE THREAD

**Issue by riki-takahashi** [riki-takahashi/GrpMng#3]
大量データが一覧画面で表示される場合、検索機能・ページング機能を実装
・案件一覧
・売上目標一覧

**Comment by iccha** [comment]
モバイル系画面を意識して、従来のPC画面の実装を共通化
教えて頂いたページネーションクラス（pagination class）を使用予定。
・　実装対象
　　　　１．売上目標情報（検索項目は、「担当グループ」と「売上期間」）。
　　　　　　　　こちらの検索機能が比較的シンプルなので優先
　　　　　　　　実装方法OK。
　　　　　　　　ANDで絞込みするよう修正済

　　　　２．案件情報
　　　　　　　　検索項目は以下の通り
　　　　　　　　　　・案件名（Likeであいまい検索）
　　　　　　　　　　・担当グループ（ドロップダウンリスト）
　　　　　　　　　　・担当者（ドロップダウンリスト）
　　　　　　　　　　・開始日（範囲指定　片方が空白なら上限いっぱいまで）
　　　　　　　　　　・終了日（同上）
　　　　　　　　　　・納品日（同上）
　　　　　　　　　　・売上日（同上）
　　　　　　　　　　・エンドユーザー（Likeであいまい検索）
　　　　　　　　　　・受注元（Likeであいまい検索）
　　　　　　　　　　・備考（Likeであいまい検索）

**Comment by iccha** [comment]
【参考】
FuelPHPのVer.1.4で構文が大きく変わりました。
http://fuelphp.jp/docs/1.7/classes/pagination.html
の最下段をごらんください。
